PROJECT := main

SEARCH :=

HEADERS := $(wildcard graphics/*.hpp)

SOURCES := $(wildcard graphics/*.cpp)

TARGET := native

SERIAL_PORT := COM3

#HEAP := BMPTK

RUN_PAUSE := echo "Run complete"

#include $(RTOS)/makefile.inc
include $(HWLIB)/makefile.inc