PROJECT := main

SEARCH :=

HEADERS := stl.hpp

SOURCES :=


TARGET := native

SERIAL_PORT := COM3

#HEAP := BMPTK

RUN_PAUSE := echo "Run complete"

PROJECT_CPP_FLAGS += -fexceptions

#include $(RTOS)/makefile.inc
include $(HWLIB)/makefile.inc
