PROJECT := main

SEARCH :=

HEADERS := circle.hpp
HEADERS += circle.hpp
HEADERS += drawable.hpp
HEADERS += exception.hpp
HEADERS += factory.hpp
HEADERS += picture.hpp

SOURCES := circle.cpp
SOURCES += drawable.cpp
SOURCES += picture.cpp

TARGET := native

SERIAL_PORT := COM3

#HEAP := BMPTK

RUN_PAUSE := echo "Run complete"

PROJECT_CPP_FLAGS += -fexceptions

#include $(RTOS)/makefile.inc
include $(HWLIB)/makefile.inc
