PROJECT := main
SEARCH :=
HEADERS := board_builder.hpp command_line_interface.hpp game_interface.hpp game_logic.hpp graphical_user_interface.hpp game_moves.hpp game_data.hpp tic_tac_toe_setup.hpp
SOURCES := board_builder.cpp command_line_interface.cpp game_logic.cpp graphical_user_interface.cpp game_moves.cpp tic_tac_toe_setup.cpp
TARGET := native
RUN_PAUSE := echo "Run completed"
PROJECT_CPP_FLAGS += -fexceptions
include $(HWLIB)/makefile.inc
